version: "3.8"

services:
  postgresql:
    image: "postgres:latest"
    ports:
      - "5452:5432"
    env_file:
      - env/postgre.env
    volumes:
      - db:/var/lib/postgresql/data
  nats-streaming:
    image: "nats-streaming:latest"
    ports:
      - "4222:4222"
      - "8222:8222"
volumes:
  db: